import { secondsToTicks } from "../seconds-to-ticks";
import type { CharacterDefinition } from "./types";

export const DEFAULT_CHARACTERS: readonly CharacterDefinition[] = [
  {
    id: "reimu",
    name: "博丽灵梦",
    cost: 4,
    roleClass: "suppress",
    moveSpeed: "medium",
    ammoCapacity: 5,
    reloadTicks: secondsToTicks(4),
    fireRate: "medium",
    bulletSpeed: "low",
    ammoPolicy: "reset_to_zero_then_fill",
    description: "低速诱导弹与清弹 bomb，适合压制弹幕空间。",
    normalAttackId: "reimu_homing_shot",
    bombId: "reimu_clear_bomb",
    gallery: {
      portraitAsset: "assets/characters/reimu/portrait.png",
      attackPreviewAsset: "assets/characters/reimu/attack-preview.png",
    },
  },
  {
    id: "marisa",
    name: "魔理沙",
    cost: 5,
    roleClass: "sniper",
    moveSpeed: "high",
    ammoCapacity: 2,
    reloadTicks: secondsToTicks(3),
    fireRate: "low",
    bulletSpeed: "high",
    ammoPolicy: "reset_to_zero_then_fill",
    description: "高速激光与长前摇魔炮，爆发强但动作约束明显。",
    normalAttackId: "marisa_laser",
    bombId: "marisa_master_spark",
    gallery: {
      portraitAsset: "assets/characters/marisa/portrait.png",
      attackPreviewAsset: "assets/characters/marisa/attack-preview.png",
    },
  },
  {
    id: "sakuya",
    name: "咲夜",
    cost: 4,
    roleClass: "assault",
    moveSpeed: "medium",
    ammoCapacity: 3,
    reloadTicks: secondsToTicks(3),
    fireRate: "medium",
    bulletSpeed: "medium",
    ammoPolicy: "reset_to_zero_then_fill",
    description: "平行双弹和时间停止 bomb，擅长近中距离压迫。",
    normalAttackId: "sakuya_parallel_knives",
    bombId: "sakuya_time_stop",
    gallery: {
      portraitAsset: "assets/characters/sakuya/portrait.png",
      attackPreviewAsset: "assets/characters/sakuya/attack-preview.png",
    },
  },
];