export type CharacterId =
  | "reimu"
  | "marisa"
  | "sakuya"
  | "demo_assault_1"
  | "demo_assault_2"
  | "demo_assault_3"
  | "demo_assault_4"
  | "demo_assault_5"
  | "demo_assault_6"
  | "demo_suppress_1"
  | "demo_suppress_2"
  | "demo_suppress_3"
  | "demo_suppress_4"
  | "demo_suppress_5"
  | "demo_suppress_6"
  | "demo_scout_1"
  | "demo_scout_2"
  | "demo_scout_3"
  | "demo_scout_4"
  | "demo_scout_5"
  | "demo_scout_6"
  | "demo_sniper_1"
  | "demo_sniper_2"
  | "demo_sniper_3"
  | "demo_sniper_4"
  | "demo_sniper_5"
  | "demo_sniper_6";
export type AbilityCardId =
  | "extra_life"
  | "ember"
  | "backdoor"
  | "multi_shot"
  | "spirit_strike_card"
  | "demo_passive_1"
  | "demo_passive_2"
  | "demo_passive_3"
  | "demo_passive_4"
  | "demo_passive_5"
  | "demo_passive_6"
  | "demo_active_1"
  | "demo_active_2"
  | "demo_active_3"
  | "demo_active_4"
  | "demo_active_5"
  | "demo_active_6";
export type MapId = "arena_standard";
export type PlayerId = "player-1" | "player-2";
