export type CharacterId =
  | "reimu"
  | "marisa"
  | "sakuya"
  | "cirno"
  | "youmu"
  | "ellen"
  | "kaguya"
  | "reisen"
  | "yuyuko"
  | "yukari"
  | "flandre"
  | "iku";
export type AbilityCardId =
  | "extra_life"
  | "ember"
  | "backdoor"
  | "multi_shot"
  | "hakkero"
  | "spirit_strike_card"
  | "invisibility_cloth"
  | "extension"
  | "graze_lover"
  | "sakura_charm"
  | "whitecat"
  | "tanuki_helper";
export type MapId =
  | "hakurei_shrine"
  | "mist_lake"
  | "bamboo_lost"
  | "mana_forest"
  | "x_shoot_range"
  | "collaborate_test_arena"
  | "collaborate_test_arena_2"
  | "shoot_range";
