name: 同步文档到 Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/wiki/**"
      - ".github/workflows/sync-wiki.yml"

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 同步文件夹到 Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/wiki/
          token: ${{ github.token }}
